version: '3.8'

services:
  nginx:
    container_name: docker_env_nginx
    image: nginx:latest # stable version
    networks:
      - server
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      # - ./nginx/ssl:/ssl
      - ./app:/var/www/html
    restart: always

  php:
    container_name: docker_env_php
    image: php_composer
    build:
      context: ./php
      dockerfile: dockerfile
    ports:
      - "9000:9000"
    networks:
      - server
      - data
    volumes:
      - ./app:/var/www/html
    restart: always

  redis:
    container_name: docker_env_redis
    image: redis:latest # stable version
    ports:
      - "6379:6379"
    networks:
      - data
    restart: always
    
  mysql:
    container_name: docker_env_mysql
    ports:
      - "3306:3306"
    image: mysql:5.7
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - data
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  phpmyadmin:
    container_name: docker_env_phpmyadmin
    image: phpmyadmin:5.2.0
    networks:
      - data
    ports:
      - 8000:80
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
networks:
  server:
  data: