# Dockerfile
FROM php:7.4-fpm

WORKDIR /var/www/html/

RUN apt-get update && \ 
    apt-get install -y libpq-dev libpng-dev libzip-dev zip vim && \
    apt-get install sudo

RUN docker-php-ext-install pgsql pdo_pgsql gd zip && \
    docker-php-ext-enable opcache

# To use mysql, install pdo pdo_mysql instead of pgsql pdo_pgsql

# Install composer Latest
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php -r "if (hash_file('sha384', 'composer-setup.php') === '55ce33d7678c5a611085589f1f3ddf8b3c52d662cd01d4ba75c0ee0459970c2200a51f492d557530c71c15d8dba01eae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && \
    php composer-setup.php && \
    php -r "unlink('composer-setup.php');" && \
    mv composer.phar /usr/bin/composer